# Generated by Django 3.2.12 on 2024-06-14 22:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(default=datetime.datetime.now)),
                ('gender', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chef_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=100, null=True)),
                ('lieu', models.CharField(max_length=100, null=True)),
                ('date_debit', models.DateField()),
                ('date_fin', models.DateField()),
                ('description_projet', models.CharField(max_length=100, null=True)),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_rapport', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('date', models.DateField()),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.personnel')),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Perdieme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_perdieme', models.CharField(max_length=100, null=True)),
                ('montant', models.IntegerField()),
                ('date_transaction', models.DateField()),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_materiel', models.CharField(max_length=100, null=True)),
                ('type_materiel', models.CharField(max_length=100, null=True)),
                ('quantite_materiel', models.CharField(max_length=100, null=True)),
                ('qualite', models.CharField(max_length=100, null=True)),
                ('projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.projet')),
            ],
        ),
    ]
