# Generated by Django 3.2.12 on 2024-06-14 23:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='phone',
        ),
        migrations.AddField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='telephone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
