# Generated by Django 3.2.12 on 2024-06-15 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20240614_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='date_enre',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
    ]
