# Generated by Django 3.2.12 on 2024-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_personnel_date_enre'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='prenom',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
