# Generated by Django 3.2.12 on 2024-06-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20240615_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='prenom',
        ),
        migrations.AddField(
            model_name='personnel',
            name='nom_prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
