# Generated by Django 3.2.12 on 2024-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20240615_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='date_debit',
        ),
        migrations.AddField(
            model_name='projet',
            name='date_debut',
            field=models.DateField(null=True),
        ),
    ]
