# Generated by Django 3.2.12 on 2024-06-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20240616_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='date_d_enregistrement',
            field=models.DateField(null=True),
        ),
    ]
