# Generated by Django 3.2.12 on 2024-06-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_materiel_date_d_enregistrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='perdieme',
            name='code_transaction_numero_bordereau',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
